# These are the auth resources that allow a job to work with a statefulset
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octopus-drain
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: octopus-drain-role
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-9"
rules:
  - apiGroups: ["apps/v1", "apps", ""]
    resources: ["statefulsets", "pods"]
    verbs: ["patch", "get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: octopus-drain-rolebinding
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-8"
subjects:
  - kind: ServiceAccount
    name: octopus-drain
    apiGroup: ""
roleRef:
  kind: Role
  name: octopus-drain-role
  apiGroup: ""