apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexus.fullname" . }}-properties
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
data:
  nexus.properties: |
    {{- range .Values.properties }}
    {{ . }}
    {{- end }}
